

1. `HttpException`  生成错误消息实例 接收两个参数 第一个错误提示语，第二个状态码

   ```js
   
     findOne(id: string) {
       const coffee = this.coffees.find((item) => item.id === +id);
       if (!coffee) {
         throw new HttpException(`Coffee #${id} not found`, HttpStatus.NOT_FOUND);
       }
       return coffee;
     }
   
   	// http://localhost:3000/coffees/123
   	// {
     //  	"statusCode": 404,
     //  	"message": "Coffee #123 not found"
     // }
   ```

   

2. NotFoundException 生成错误消息 not found 实例 接收一个错误消失字符串

   ```js
     findOne(id: string) {
       const coffee = this.coffees.find((item) => item.id === +id);
       if (!coffee) {
         throw new NotFoundException(`Coffee #${id} not found`);
       }
       return coffee;
     }
     
     // http://localhost:3000/coffees/123
   	// {
     //  	"statusCode": 404,
     //  	"message": "Coffee #123 not found",
     // 		"error": "Not Found"
     // }
   ```

   